{{- if and (not .Values.nodeComponentOnly) (.Values.sidecars.metadataLabeler.enabled) -}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ebs-csi-metadata-labeler-binding
  labels:
    {{- include "aws-ebs-csi-driver.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.controller.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ebs-metadata-labeler-role
{{- end -}}
