{{- if not .Values.nodeComponentOnly -}}
apiVersion: {{ ternary "storage.k8s.io/v1" "storage.k8s.io/v1beta1" (semverCompare ">=1.18.0-0" .Capabilities.KubeVersion.Version) }}
kind: CSIDriver
metadata:
  name: ebs.csi.aws.com
  labels:
    {{- include "aws-ebs-csi-driver.labels" . | nindent 4 }}
spec:
  attachRequired: true
  podInfoOnMount: false
  {{- if semverCompare ">=1.33.0-0" .Capabilities.KubeVersion.Version }}
  {{- if eq (.Values.nodeAllocatableUpdatePeriodSeconds | int) -1 }}
  nodeAllocatableUpdatePeriodSeconds: {{ (regexMatch "metadata-labeler" (.Values.node.metadataSources | default "")) | ternary "300" "10" }}
  {{- else if .Values.nodeAllocatableUpdatePeriodSeconds }}
  nodeAllocatableUpdatePeriodSeconds: {{ .Values.nodeAllocatableUpdatePeriodSeconds }}
  {{- end }}
  {{- end }}
  {{- if not .Values.useOldCSIDriver }}
  fsGroupPolicy: File
  {{- end }}
  {{- if .Values.node.selinux }}
  seLinuxMount: true
  {{- end }}
{{- end }}
